name: Run certain tasks on repository

on:
  workflow_dispatch

env:
  CACHE_PATHS: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  print_type_sizes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: top-type-sizes
      
      - name: Run type sizes
        run: |
          RUSTFLAGS=-Zprint-type-sizes cargo +nightly build -j 1 > type-sizes-input.txt
          top-type-sizes --remove-wrappers < type-sizes-input.txt > type-sizes.txt

      - uses: actions/upload-artifact@v4
        with:
          name: type-sizes
          path: type-sizes.txt
          retention-days: 7
          