name: performance
run-name: Performance on ${{ github.ref_name }}

on: workflow_dispatch

env: { CARGO_TERM_COLOR: always }

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    env: { GH_TOKEN: '${{ github.token }}' }

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: kaleidawave/release-downloader@improvements
        env: { GH_TOKEN: '${{ env.GH_TOKEN }}' }
        with:
          items: kaleidawave/experiments@assets[shell-language|spectra],sharkdp/hyperfine@v1.19.0

      # TODO is there a way to cache this?
      - name: Build latest version of demo.tsx
        run: |
          curl https://gist.githubusercontent.com/kaleidawave/81066f322ed574b3373e27770137013f/raw/b04dcc0bc60e6331008bdd578b98224cc07d5d42/all.tsx > demo.tsx

          # TODO temp
          cat demo.tsx

          # in the future
          # spectra list checker/specification/specification.md --cases-with-splitter '~~~' > total.ts 
          # cargo update derive-enum-from-into
          # cargo run -p ezno-parser --example combine_blocks total.ts --out demo.tsx

      # get other binaries and last

      - name: Build latest version of binary
        shell: bash
        run: cargo build --release

      # start of performance

      - name: Compare checker performance
        shell: shell-language {0}
        run: |
          let to = env GITHUB_STEP_SUMMARY
          hyperfine -N -i './target/release/ezno check demo.tsx'
          append $to "### Checking `demo.tsx`\n"
          append $to "```shell\n$output\n```"

      - name: Print input
        if: false
        shell: shell-language {0}
        run: |
          let to = env GITHUB_STEP_SUMMARY
          let content = read ./demo.tsx
          append $to "<details><summary>Input</summary>\n"
          append $to "```tsx\n$content\n```\n</details>"
          
      - name: Run checker performance on file
        id: performance
        continue-on-error: true
        shell: shell-language {0}
        run: |
          let to = env GITHUB_STEP_SUMMARY
          append $to "#### check demo.tsx"

          let out = run ./target/release/ezno check demo.tsx --timings --max-diagnostics all --merge-stdout-and-stderr

          # let diagnostics = rbefore $out "---" then trim
          let statistics = rafter $out "---" then trim

          append $to "<details><summary>Statistics for $file check demo.tsx</summary>\n"
          append $to "```\n$statistics\n```\n</details>\n"

      - name: Run checker performance on file 10
        shell: shell-language {0}
        run: |
          let to = env GITHUB_STEP_SUMMARY
          let large = read "./demo.tsx" then repeat 10
          write "./large.tsx" $large

          append $to "#### check large.tsx"
          let output = run hyperfine -N -i './target/release/ezno check large.tsx'
          append $to "```shell\n$output\n```\n"

          append $to "<details><summary>Statistics for $file check large.tsx</summary>\n"
          
          let out = run ./target/release/ezno check large.tsx --timings --merge-stdout-and-stderr
          let statistics = rafter $out "---" then trim
          append $to "```\n$statistics\n```\n"
          append $to "</details>\n"

      # TODO wip
      - uses: actions/checkout@v6
        with: { repository: kaleidawave/depict, ref: cli-improvements, path: depict }

      - name: Install and run depict
        working-directory: todo install
        run: | 
          cargo r -- install-sde
          cargo r -- sde ../binaries/latest/ezno check ../demo.tsx

      # final steps

      # upload to projects site
